#include "/Engine/Private/Common.ush"
#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"


float4 MainPS(float4 SvPosition : SV_POSITION) : SV_Target0
{
    float t = saturate(SvPosition.y * View.ViewSizeAndInvSize.w);

    const float3 colLow = float3(0.02, 0.08, 0.25);
    const float3 colHigh = float3(0.25, 0.75, 1.00);
    float3 color = lerp(colLow, colHigh, t);

    return float4(color, 1.0);
}
